import type { ContextDocumentFormState } from "../types";

export function createDefaultContextDocumentForm(): ContextDocumentFormState {
  const today = new Date().toISOString().slice(0, 10);
  return {
    scope: "client",
    contentType: "briefing",
    mainCategory: "",
    subcategory: "",
    sector: "",
    title: "",
    executiveSummary: "",
    author: "",
    internalOwner: "",
    sourceOrigin: "",
    language: "pt-BR",
    reliabilityLevel: "medium",
    confidentiality: "internal",
    visibility: "agency_only",
    tagsRequired: "",
    additionalKeywords: "",
    citedEntities: "",
    relatedPlatforms: "",
    iaObjective: "",
    documentCreatedAt: today,
    competenceStart: today,
    competenceEnd: today,
    validUntil: "",
    isEvergreen: false,
    status: "active",
    replacesAnother: false,
    replacesDocumentId: "",
    version: "1.0",
    priorityUse: "normal",
    contextRole: "complementary",
    allowAnalysis: true,
    allowChat: true,
    isOfficial: false,
    isHistorical: false,
    strategicRelevance: "",
    uploadMode: "text",
    textContent: "",
  };
}
